name: flutter_video
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^2.1.6
  video_player: ^1.0.1
  cupertino_icons: ^1.0.0
  amazon_s3_cognito: ^0.5.2
  pedantic: ^1.9.2
  flutter_cache_manager: ^2.1.1
  toast: ^0.1.5
  flutter_ffmpeg: ^0.3.0
  flutter_riverpod: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/