/// Flutter icons Flutter_video
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Flutter_video
///      fonts:
///       - asset: fonts/Flutter_video.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FlutterVideo {
  FlutterVideo._();

  static const _kFontFam = 'Flutter_video';
  static const String _kFontPkg = null;

  static const IconData video = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
